### ISSUE TITLE
(Potential) DIMOWA ModDebugger failure with connectedSck.Close(); or SetServerIsUp(false);

### ISSUE THREAD

**Issue by clifflocked** [ShoosGun/DIMOWA#2]
I was using the Mod Debugger, and everything loads fine and works fine. But when I close the game window, the Mod Debugger prints "Closing Server..." but not "Server Closed". I looked at the code, and it seems as though it is a issue with `connectedSck.Close();` or `SetServerIsUP(false);` (lines 139 and 140)

**Comment by loco-choco** [comment]
That's really odd, I'm not sure what might have happen, neither the "developer version" nor the release version showed me that strange behaviour: 
<img width="429" alt="_" src="https://user-images.githubusercontent.com/58634087/103695399-414bf200-4f7b-11eb-8599-dcd6f2df6635.png">
 If it is happening everytime you use the debugger, I'll try to search more to understand what caused this.

**Comment by clifflocked** [comment]
I found the reason why its happening; I always close the Alpha window by clicking the windows close button, but the Debugger can only close the server if you click the "Exit Game" button.
<img width="674" alt="works" src="https://user-images.githubusercontent.com/72527185/104350331-e5242900-54b8-11eb-895a-14cd34ddc4a3.png">
